//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCION_INFO
    {
        public ACCION_INFO()
        {
            this.LOG_INFO = new HashSet<LOG_INFO>();
        }
    
        public int IdAccionInfo { get; set; }
        public string NombreAccionInfo { get; set; }
    
        public virtual ICollection<LOG_INFO> LOG_INFO { get; set; }
    }
}
