//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARBOL_OU
    {
        public decimal Id { get; set; }
        public Nullable<int> IdOu { get; set; }
        public Nullable<int> IdPadreOu { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string Ldap { get; set; }
    }
}
