//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_CUENTA_USUARIO
    {
        public decimal IdEstadoCuentaUsuario { get; set; }
        public string CuentaAd { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Correo { get; set; }
        public string Descripcion { get; set; }
        public string Dominio { get; set; }
        public bool CreadoAd { get; set; }
        public bool Sincronizado { get; set; }
        public decimal LicenciaId { get; set; }
        public bool Habilitado { get; set; }
        public bool Eliminado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string CodigoLicencia { get; set; }
        public bool Vigente { get; set; }
        public bool LicenciaAsignada { get; set; }
        public string Clave { get; set; }
    
        public virtual LICENCIAS_O365 LICENCIAS_O365 { get; set; }
    }
}
