//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_SINCRONIZACION
    {
        public decimal Id { get; set; }
        public bool Sincronizando { get; set; }
        public Nullable<System.DateTime> FechaMvto { get; set; }
        public string UsuarioModificacion { get; set; }
        public string Modulo { get; set; }
    }
}
