//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICENCIAS_O365
    {
        public LICENCIAS_O365()
        {
            this.ESTADO_CUENTA_USUARIO = new HashSet<ESTADO_CUENTA_USUARIO>();
            this.MANTENEDOR_LICENCIA = new HashSet<MANTENEDOR_LICENCIA>();
        }
    
        public decimal IdLicencia { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public bool Vigente { get; set; }
    
        public virtual ICollection<ESTADO_CUENTA_USUARIO> ESTADO_CUENTA_USUARIO { get; set; }
        public virtual ICollection<MANTENEDOR_LICENCIA> MANTENEDOR_LICENCIA { get; set; }
    }
}
