//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_INFO
    {
        public decimal IdInfo { get; set; }
        public string MsgInfo { get; set; }
        public string UserInfo { get; set; }
        public System.DateTime FechaInfo { get; set; }
        public int AccionIdInfo { get; set; }
    
        public virtual ACCION_INFO ACCION_INFO { get; set; }
    }
}
