//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENEDOR_LICENCIA
    {
        public decimal IdMantenedorLicencia { get; set; }
        public string Codigo { get; set; }
        public decimal RolCargoId { get; set; }
        public decimal LicenciaId { get; set; }
        public bool Vigente { get; set; }
    
        public virtual LICENCIAS_O365 LICENCIAS_O365 { get; set; }
        public virtual ROL_CARGO ROL_CARGO { get; set; }
    }
}
