//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;
using System.Data.Common;
using System.Data.SqlClient;

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdmSysWebEntities : DbContext
    {
        public AdmSysWebEntities()
            : base("name=AdmSysWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccionInfo> ACCION_INFO { get; set; }
        public virtual DbSet<LogInfo> LOG_INFO { get; set; }
    }
}
