//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdmSysWebEntities : DbContext
    {
        public AdmSysWebEntities()
            : base("name=AdmSysWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCION_INFO> ACCION_INFO { get; set; }
        public virtual DbSet<ESTADO_ASIGNACION_LICENCIA> ESTADO_ASIGNACION_LICENCIA { get; set; }
        public virtual DbSet<ESTADO_CUENTA_USUARIO> ESTADO_CUENTA_USUARIO { get; set; }
        public virtual DbSet<ESTADO_SINCRONIZACION> ESTADO_SINCRONIZACION { get; set; }
        public virtual DbSet<LICENCIAS_O365> LICENCIAS_O365 { get; set; }
        public virtual DbSet<LOG_INFO> LOG_INFO { get; set; }
        public virtual DbSet<MANTENEDOR_LICENCIA> MANTENEDOR_LICENCIA { get; set; }
        public virtual DbSet<PERFIL_USUARIO> PERFIL_USUARIO { get; set; }
        public virtual DbSet<ROL_CARGO> ROL_CARGO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
