//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL_USUARIO
    {
        public PERFIL_USUARIO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int IdPerfil { get; set; }
        public string NombrePerfil { get; set; }
        public bool Vigente { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
