//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE_LICENCIA
    {
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string SamAccountName { get; set; }
        public string Description { get; set; }
        public string UpnPrefijo { get; set; }
        public string InfoString { get; set; }
        public string Licenses { get; set; }
        public string DistinguishedName { get; set; }
    }
}
