//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL_CARGO
    {
        public ROL_CARGO()
        {
            this.MANTENEDOR_LICENCIA = new HashSet<MANTENEDOR_LICENCIA>();
        }
    
        public decimal IdRolCargo { get; set; }
        public string Nombre { get; set; }
        public bool Vigente { get; set; }
    
        public virtual ICollection<MANTENEDOR_LICENCIA> MANTENEDOR_LICENCIA { get; set; }
    }
}
