//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.AdmExpertSys.WEB.Core.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public decimal Id { get; set; }
        public string Usuario1 { get; set; }
        public Nullable<int> PerfilId { get; set; }
        public bool Visible { get; set; }
        public bool EsAdm { get; set; }
    
        public virtual PERFIL_USUARIO PERFIL_USUARIO { get; set; }
    }
}
